title: Encom
author: Marcus Lindblom
email: m@marcuslindblom.com
description: > # this means to ignore newlines until "twitter_username:"
  Encom goes public
  
show_excerpts: true # set to true to show excerpts on the homepage

header_pages:
  - what-we-do.md
  - our-story.md
  - team.md
  
plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: minima